// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroesAPI.Data;

#nullable disable

namespace SuperHeroesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SuperHeroesAPI.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeHeroi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Superpoderes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = "1,85m",
                            DataNascimento = "18/04/1938",
                            Nome = "Clark Kent",
                            NomeHeroi = "Superman",
                            Peso = "90kg",
                            Superpoderes = "Força, Voo, Visão de Raio-X"
                        },
                        new
                        {
                            Id = 2,
                            Altura = "1,85m",
                            DataNascimento = "19/03/1939",
                            Nome = "Bruce Wayne",
                            NomeHeroi = "Batman",
                            Peso = "95kg",
                            Superpoderes = "Inteligência, Habilidade em Luta, Tecnologia Avançada"
                        },
                        new
                        {
                            Id = 3,
                            Altura = "1,83m",
                            DataNascimento = "21/03/1939",
                            Nome = "Diana Prince",
                            NomeHeroi = "Mulher Maravilha",
                            Peso = "74kg",
                            Superpoderes = "Força, Voo, Luta com Espada"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
